spring:
  data:
    mongodb:
      username: gabriel
      password: gabriel
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
